### PR TITLE
endpoint for getting similarity index with another user, close #35

### LINKED ISSUE #35: GET similarity index

### PR DESCRIPTION
**Pull request by lozy219**

### CODE REVIEW

**Comment by lozy219** [comment]
the calculation need to be revised. I feel that it makes more sense to compare the choice they picked; because if both of the users like something, that means they are 'similar'. However, comparing the choices that they commonly do not pick might not be necessary.

**Comment by xbili** [comment]
@lozy219 Hmm I thought we discussed about this, it is because if we do not calculate the choices they commonly do not pick, users can simply select all choices and they'll always get all the matches?

**Comment by ianngiaw** [comment]
@lozy219 maybe we could give more weight to matches due to similar choices than matches due to similar non-choices. For example, both if A and B chose Chinese food so we add 1, and if both didn't select Western food so we add 0.5

**Comment by xbili** [comment]
@ianngiaw Hmm that sounds interesting yeah.

**Comment by lozy219** [comment]
Now I calculate the similarity index in this way: (#common choices) /
(#total choices they choose - #common choices)

Suppose for a question, user 1 chooses a, b, and user2 chooses b, c, their
similarity index will be 1/3=0.333. If user1 chooses a, b, user2 chooses
abcdefghi, their similarity index will be 2/9=0.22222

In other words, the choices both of them don't pick will also be considered.

**Comment by ianngiaw** [comment]
@lozy219 that works too. I have a few amendments for your PR, I'll make the changes before i merge it in

**Comment by ianngiaw** [comment]
I changed the deletion of every single one of the user's answers to just deleting every response of the user's answers with the same question id

**Pull request merged**
