### PR TITLE
[WIP] Handles GET for ProfileQuestion

### LINKED ISSUE #16: POST profile question answer

### PR DESCRIPTION
**Pull request by xbili**
Closes #16 

Haven't found a good way to get the current user with the token in the user controller yet.

### CODE REVIEW

**Comment by ianngiaw** [comment]
Actually if you look at the verifyToken method in app/controllers/token.js, I put the user object under req.user, so you don't need to get the user from the db again, just use the req.user object.

**Comment by xbili** [comment]
@ianngiaw Ah, just saw it. Thanks!

**Comment by ianngiaw** [comment]
no prob. anyway i'm updating authentication to use a more web style storing the token in a user's cookies, so I don't think there will be a verifyToken function anymore when I'm done with it.

**Comment by xbili** [comment]
@ianngiaw :+1:

**Pull request merged**
